updated lint rule for actions

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -40,11 +40,18 @@ jobs:
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
     
     - name: Lint with flake8
+      continue-on-error: true
       run: |
-        # stop the build if there are Python syntax errors or undefined names
+        # Stop the build if there are Python syntax errors or undefined names.
         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
-        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+        # Any remaining Flake8 error also fails the workflow.
+        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
+
+    - name: Check if 'Lint with flake8' step failed
+      if: steps.flake8.outcome != 'success'
+      run: |
+        echo "flake8 fails"
+        exit 1
     
     - name: Test with pytest
       run: |
